// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FibonacciClient is the client API for Fibonacci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonacciClient interface {
	GetNext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FibonacciNumber, error)
	GetFirstN(ctx context.Context, in *FirstNQuery, opts ...grpc.CallOption) (*FirstNResponse, error)
	Stream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Fibonacci_StreamClient, error)
}

type fibonacciClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonacciClient(cc grpc.ClientConnInterface) FibonacciClient {
	return &fibonacciClient{cc}
}

func (c *fibonacciClient) GetNext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FibonacciNumber, error) {
	out := new(FibonacciNumber)
	err := c.cc.Invoke(ctx, "/api.Fibonacci/GetNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibonacciClient) GetFirstN(ctx context.Context, in *FirstNQuery, opts ...grpc.CallOption) (*FirstNResponse, error) {
	out := new(FirstNResponse)
	err := c.cc.Invoke(ctx, "/api.Fibonacci/GetFirstN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibonacciClient) Stream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Fibonacci_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Fibonacci_ServiceDesc.Streams[0], "/api.Fibonacci/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &fibonacciStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fibonacci_StreamClient interface {
	Recv() (*FibonacciNumber, error)
	grpc.ClientStream
}

type fibonacciStreamClient struct {
	grpc.ClientStream
}

func (x *fibonacciStreamClient) Recv() (*FibonacciNumber, error) {
	m := new(FibonacciNumber)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FibonacciServer is the server API for Fibonacci service.
// All implementations must embed UnimplementedFibonacciServer
// for forward compatibility
type FibonacciServer interface {
	GetNext(context.Context, *emptypb.Empty) (*FibonacciNumber, error)
	GetFirstN(context.Context, *FirstNQuery) (*FirstNResponse, error)
	Stream(*emptypb.Empty, Fibonacci_StreamServer) error
	mustEmbedUnimplementedFibonacciServer()
}

// UnimplementedFibonacciServer must be embedded to have forward compatible implementations.
type UnimplementedFibonacciServer struct {
}

func (UnimplementedFibonacciServer) GetNext(context.Context, *emptypb.Empty) (*FibonacciNumber, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNext not implemented")
}
func (UnimplementedFibonacciServer) GetFirstN(context.Context, *FirstNQuery) (*FirstNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirstN not implemented")
}
func (UnimplementedFibonacciServer) Stream(*emptypb.Empty, Fibonacci_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFibonacciServer) mustEmbedUnimplementedFibonacciServer() {}

// UnsafeFibonacciServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonacciServer will
// result in compilation errors.
type UnsafeFibonacciServer interface {
	mustEmbedUnimplementedFibonacciServer()
}

func RegisterFibonacciServer(s grpc.ServiceRegistrar, srv FibonacciServer) {
	s.RegisterService(&Fibonacci_ServiceDesc, srv)
}

func _Fibonacci_GetNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciServer).GetNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Fibonacci/GetNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciServer).GetNext(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibonacci_GetFirstN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirstNQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciServer).GetFirstN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Fibonacci/GetFirstN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciServer).GetFirstN(ctx, req.(*FirstNQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibonacci_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FibonacciServer).Stream(m, &fibonacciStreamServer{stream})
}

type Fibonacci_StreamServer interface {
	Send(*FibonacciNumber) error
	grpc.ServerStream
}

type fibonacciStreamServer struct {
	grpc.ServerStream
}

func (x *fibonacciStreamServer) Send(m *FibonacciNumber) error {
	return x.ServerStream.SendMsg(m)
}

// Fibonacci_ServiceDesc is the grpc.ServiceDesc for Fibonacci service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fibonacci_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Fibonacci",
	HandlerType: (*FibonacciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNext",
			Handler:    _Fibonacci_GetNext_Handler,
		},
		{
			MethodName: "GetFirstN",
			Handler:    _Fibonacci_GetFirstN_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Fibonacci_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/fibonacci.proto",
}
