// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/biblioteca.proto

package biblioteca

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn                 string   `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_299b71d056f5420c, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Book) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type BookRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_299b71d056f5420c, []int{1}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Book)(nil), "biblioteca.Book")
	proto.RegisterType((*BookRequest)(nil), "biblioteca.BookRequest")
}

func init() { proto.RegisterFile("api/biblioteca.proto", fileDescriptor_299b71d056f5420c) }

var fileDescriptor_299b71d056f5420c = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4e, 0xf3, 0x30,
	0x14, 0x84, 0xff, 0xa4, 0x69, 0x7e, 0xf1, 0x2a, 0x21, 0x64, 0x55, 0x60, 0x15, 0x90, 0xa2, 0x6c,
	0xc8, 0x2a, 0x91, 0xe8, 0x09, 0x88, 0xba, 0xe9, 0x36, 0x3d, 0x41, 0x6c, 0x1e, 0xee, 0x13, 0x69,
	0x9f, 0x71, 0x1c, 0x10, 0xb7, 0xe0, 0xc8, 0xa8, 0x0e, 0x82, 0xa8, 0x3b, 0xcf, 0x37, 0x63, 0x79,
	0x3c, 0xb0, 0x6c, 0x2d, 0x55, 0x8a, 0x54, 0x47, 0xec, 0x51, 0xb7, 0xa5, 0x75, 0xec, 0x59, 0xc0,
	0x1f, 0x59, 0xdd, 0x1a, 0x66, 0xd3, 0x61, 0x15, 0x1c, 0x35, 0xbc, 0x54, 0x78, 0xb0, 0xfe, 0x73,
	0x0c, 0xe6, 0x5f, 0x11, 0x24, 0x35, 0xf3, 0xab, 0xb8, 0x84, 0x78, 0xbb, 0x91, 0x51, 0x16, 0x15,
	0xb3, 0x26, 0xde, 0x6e, 0xc4, 0x12, 0xe6, 0x9e, 0x7c, 0x87, 0x32, 0xce, 0xa2, 0xe2, 0xa2, 0x19,
	0x85, 0xb8, 0x86, 0xb4, 0x1d, 0xfc, 0x9e, 0x9d, 0x9c, 0x05, 0xfc, 0xa3, 0x84, 0x80, 0x84, 0x7a,
	0x75, 0x94, 0x49, 0xa0, 0xe1, 0x2c, 0x32, 0x58, 0x3c, 0x63, 0xaf, 0x1d, 0x59, 0x4f, 0x7c, 0x94,
	0xf3, 0x60, 0x4d, 0xd1, 0xe9, 0x0d, 0xeb, 0x48, 0xa3, 0x4c, 0xb3, 0xa8, 0x88, 0x9b, 0x51, 0xe4,
	0xf7, 0xb0, 0x38, 0x35, 0x6a, 0xf0, 0x6d, 0xc0, 0xde, 0x9f, 0x17, 0x7b, 0x7c, 0x02, 0xa8, 0x7f,
	0x3f, 0x27, 0xd6, 0x90, 0xec, 0xf6, 0xfc, 0x21, 0x6e, 0xca, 0xc9, 0x06, 0x93, 0xeb, 0xab, 0xab,
	0x73, 0x23, 0xff, 0x57, 0x3f, 0xc0, 0x9d, 0xe6, 0x43, 0xd9, 0x76, 0x86, 0x8d, 0x23, 0x5f, 0x1a,
	0x67, 0xf5, 0x24, 0x56, 0xff, 0xdf, 0xa1, 0x7b, 0x27, 0x8d, 0x2a, 0x0d, 0x23, 0xad, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x44, 0x0d, 0xc2, 0xdc, 0x65, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BibliotecaClient is the client API for Biblioteca service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BibliotecaClient interface {
	Show(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*Book, error)
}

type bibliotecaClient struct {
	cc *grpc.ClientConn
}

func NewBibliotecaClient(cc *grpc.ClientConn) BibliotecaClient {
	return &bibliotecaClient{cc}
}

func (c *bibliotecaClient) Show(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/biblioteca.Biblioteca/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BibliotecaServer is the server API for Biblioteca service.
type BibliotecaServer interface {
	Show(context.Context, *BookRequest) (*Book, error)
}

// UnimplementedBibliotecaServer can be embedded to have forward compatible implementations.
type UnimplementedBibliotecaServer struct {
}

func (*UnimplementedBibliotecaServer) Show(ctx context.Context, req *BookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}

func RegisterBibliotecaServer(s *grpc.Server, srv BibliotecaServer) {
	s.RegisterService(&_Biblioteca_serviceDesc, srv)
}

func _Biblioteca_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BibliotecaServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biblioteca.Biblioteca/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BibliotecaServer).Show(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Biblioteca_serviceDesc = grpc.ServiceDesc{
	ServiceName: "biblioteca.Biblioteca",
	HandlerType: (*BibliotecaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Show",
			Handler:    _Biblioteca_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/biblioteca.proto",
}
