// The following directive is necessary to make the package build:

// +build ignore

// This program generates strings.go. It can be invoked by running
// go generate
package main

import (
	"html/template"
	"log"
	"os"
	"time"
)

func main() {
	f, err := os.Create("strings.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
	}{
		Timestamp: time.Now(),
	})
}

var packageTemplate = template.Must(template.New("").Parse(`
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package main

func strFunc() string {
	return "I was generated!"
}
`))
